development:
  adapter: postgresql
  encoding: unicode
  database: mvsr_development
  pool: 5
  username: "postgres"
  password: "postgres"

test:
  adapter: postgresql
  encoding: unicode
  database: mvsr_test
  pool: 5
  username: "postgres"
  password: "postgres"

production:
  adapter: postgresql
  encoding: unicode
  database: rorexpert_production
  pool: 5
  username: "postgres"
  password: "vijay123"
